enum ErrorCode {
  // Auth error code
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS",
  PASSWORD_TOO_SHORT = "PASSWORD_TOO_SHORT",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  MISSING_SESSION_ID = "MISSING_SESSION_ID",
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  IP_CHANGED = "IP_CHANGED",
  BROWSER_MISMATCH = "BROWSER_MISMATCH",

  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",

  INTERNAL_SERVER = "INTERNAL_SERVER",
  BAD_REQUEST = "BAD_REQUEST",
}

export default ErrorCode;
